### PR TITLE
Edit feature

### PR DESCRIPTION
**Pull request by hbandar**
1. added edit_transaction functionality
2. also created helper functions to edit date, cost & category
3. fixed bugs from previous version
image
image

### CODE REVIEW

**Review by tpanati — COMMENTED** [review]
Is there a possibility to not take category, date, and amount in one line and instead take it one after another as an improvisation? Just a suggestion that it might look better?

**Comment by hbandar** [comment]
Sure will work on it!

**Comment by hbandar** [comment]
image

**Comment by vyshnavi-adusumelli** [comment]
Your branch has merge conflicts. Can you fic then before merging.

**Review by vyshnavi-adusumelli — APPROVED** [review]

**Pull request merged**
