### PR TITLE
chore: Create feature history

### PR DESCRIPTION
**Pull request by vyshnavi-adusumelli**
1. Code changes to add "history" feature in discord bot
2. Fixed user input formate for date to mm-dd-YYYY in the code
3. Fixed few bugs

Screenshot 2023-10-09 at 9 46 03 AM

### CODE REVIEW

**Review by tpanati — CHANGES_REQUESTED** [review]
Looks like if there is no file in the discordData and teleData directory, we aren't able to create empty directories in the repo - that's why the .gitignore while was added intentionally as per https://stackoverflow.com/questions/115983/how-do-i-add-an-empty-directory-to-a-git-repository. Is there a possibility of not removing those files?

**Comment by tpanati** [comment]
Otherwise the functionality changes looks good!

**Review by vyshnavi-adusumelli — COMMENTED** [review]
I have re-added the gitignore files to the repository. Please take a look now.

**Review by tpanati — APPROVED** [review]
Looks good to me!

**Pull request merged**
